services:
  rest-server:
    container_name: rest-server
    build:
      context: .
      dockerfile: ./deployment/rest_server/Dockerfile
    image: rest-server:latest
    restart: unless-stopped
    ports:
      - "5000:5000"

    environment:
      - REDIS_URL
      - REDIS_PASSWORD
      - JWT_ALGORITHM
      - JWT_SECRET
      - JWT_AUDIENCE
      - POSTGRES_URL
      - POSTGRES_SCHEMA
    volumes:
      - ./logs:/src/logs
    networks:
      - demo_network
    # depends_on:
    #   rabbitmq-server:
    #     condition: service_healthy
    #   redis-server:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  demo_network:
    external: true
